exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("songs")
    .truncate()
    .then(function () {
      // Inserts seed entries
      return knex("songs").insert([
        {
          id: 1,
          track_id: "nBAJXqGmgQZdJCw0ENhXAHzh5QO",
          track_name: "rAIn oN mE (with aRIaNa gRAndE)",
          artist_name: "Lady Gaga",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 2,
          track_id: "PnYnmbPCDn9YWA6ZdW4BAbcqZj1",
          track_name: "Blinding Lights",
          artist_name: "The Weeknd",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 3,
          track_id: "SK7FgqOQTkf8sXmf4Wy4Cv7M4fu",
          track_name: "Sour Candy (with BLACKPINK)",
          artist_name: "Lady Gaga",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 4,
          track_id: "cpBiqFMXB1G1mMaQKIC7LkMgqZc",
          track_name: "Stupid Love",
          artist_name: "Lady Gaga",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 5,
          track_id: "GVGwjvYopfsYL5MroS62T0a9CEy",
          track_name: "Alice",
          artist_name: "Lady Gaga",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 6,
          track_id: "oInvrI2HY5NaHZMNerG3B30AgYR",
          track_name: "doN'T StArT nOw",
          artist_name: "Dua Lipa",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 7,
          track_id: "yzSdxQUm5lSEBJI7JBx3CfdCWVu",
          track_name: "Chromatica I",
          artist_name: "Lady Gaga",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 8,
          track_id: "To9iPnSSUXDRB8Rq86OXMEdziMo",
          track_name: "Free Woman",
          artist_name: "Lady Gaga",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 9,
          track_id: "AFzs88GwzdLTlmpAWdGEQj3SQ92",
          track_name: "911",
          artist_name: "Lady Gaga",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 10,
          track_id: "UTyeSByzGKkG1ryMChfPjAYnHKB",
          track_name: "Break My Heart",
          artist_name: "Dua Lipa",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 11,
          track_id: "t4eg3Gtt1oXLzPTpZiqzYgjfguz",
          track_name: "Fun Tonight",
          artist_name: "Lady Gaga",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 12,
          track_id: "tyPmT8AyJWW0OlpNnN6crm26r5C",
          track_name: "Chromatica II",
          artist_name: "Lady Gaga",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 13,
          track_id: "F48Wr1TiLLItFT6JC9DfakFzeeI",
          track_name: "Plastic Doll",
          artist_name: "Lady Gaga",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 14,
          track_id: "5UM6UqTEIzBmsBBGgLwqHjO0xRu",
          track_name: "Enigma",
          artist_name: "Lady Gaga",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 15,
          track_id: "nhXr8Uvsq5tPezCT9XRLO7iQfqC",
          track_name: "Replay",
          artist_name: "Lady Gaga",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 16,
          track_id: "FWv5TrAojLGdAcdITmiXq0iaxX3",
          track_name: "Babylon",
          artist_name: "Lady Gaga",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 17,
          track_id: "cvYWIGYxwrLoEaCa5I70jKT41ls",
          track_name: "1000 Doves",
          artist_name: "Lady Gaga",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 18,
          track_id: "maoHCiKnBuJrCmeWLUetqrL7Qg4",
          track_name: "Watermelon Sugar",
          artist_name: "Harry Styles",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 19,
          track_id: "tF7SvyygmIuHFqlXRYgMqIsnk74",
          track_name: "Sine From Above (with Elton John)",
          artist_name: "Lady Gaga",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 20,
          track_id: "ZyyBYstltk4OZzZkY8UUi3Gsibh",
          track_name: "Physical",
          artist_name: "Dua Lipa",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 21,
          track_id: "MSx8OlvzSobcIDfIpcXBsErCozA",
          track_name: "Say So",
          artist_name: "Doja Cat",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 22,
          track_id: "Dk3Uyj0q3HpYNtrerovDd3oHcOf",
          track_name: "Adore You",
          artist_name: "Harry Styles",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 23,
          track_id: "WRh7y0el2XiEWBMRec40RhhQ4Bx",
          track_name: "In Your Eyes",
          artist_name: "The Weeknd",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 24,
          track_id: "TRp7Bp67tU5CWh2keCFUGTm3qUb",
          track_name: "The Less I Know the Better",
          artist_name: "Tame Impala",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 25,
          track_id: "rvlSzitLtLoFFyk5PcT3Fzz0Ikf",
          track_name: "bad guy",
          artist_name: "Billie Eilish",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 26,
          track_id: "DghYIXDFMuAROATrzmp4OY3Qe9s",
          track_name: "TKN (feat. Travis Scott)",
          artist_name: "Rosalía",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 27,
          track_id: "lL1dyIJodmWG7Q6PvosNcfZEtkE",
          track_name: "ROCKSTAR (feat. Roddy Ricch)",
          artist_name: "DaBaby",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 28,
          track_id: "UrcwM5Py71rY1jNghbhvNFjlsDv",
          track_name: "This Is America",
          artist_name: "Childish Gambino",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 29,
          track_id: "cVoLAAhvC9bHoSUqgQwAHB4aROf",
          track_name: "Roses - Imanbek Remix",
          artist_name: "SAINt JHN",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 30,
          track_id: "4RmjJzuIv7V7MR0UJQyYSuEzyVD",
          track_name: "Alright",
          artist_name: "Kendrick Lamar",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 31,
          track_id: "SuH4onQSSXLMpo7kHUqqr1EjphM",
          track_name: "Toosie Slide",
          artist_name: "Drake",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 32,
          track_id: "KTkACPyLcQeK85XnpOfRJQX3jjN",
          track_name: "Savage Remix (feat. Beyoncé)",
          artist_name: "Megan Thee Stallion",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 33,
          track_id: "hWvCEk5i303EbHduBTJzOEtDZpO",
          track_name: "yankee and the brave (ep. 4)",
          artist_name: "Run the Jewels",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 34,
          track_id: "KtcaisVRfF7lQeTwfCygm7MWmdm",
          track_name: "Earfquake",
          artist_name: "Tyler, the Creator",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 35,
          track_id: "eU2e41YMFm2PZUl4huUY0Ldesyb",
          track_name: "THE SCOTTS",
          artist_name: "Scotts",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 36,
          track_id: "XoQbRZNEO3z6GIoyQQ3qNjeoDR4",
          track_name: "Circles",
          artist_name: "Post Malone",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 37,
          track_id: "65rsB6ibYugFs4jlKEEJkmwgf8w",
          track_name: "Boss Bitch",
          artist_name: "Doja Cat",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 38,
          track_id: "Fsxr9jAnPbs9YHA01XSx0oIEUXl",
          track_name: "Ooh La La (feat. Greg Nice & DJ Premier)",
          artist_name: "Run the Jewels",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 39,
          track_id: "2FNRVb5GXwBOvONLxNCphNGemec",
          track_name: "JU$T (feat. Pharrell Williams & Zack de la Rocha)",
          artist_name: "Run the Jewels",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 40,
          track_id: "oUosVfkm7KM3v8aBhy34qq9R47Z",
          track_name: "Levitating",
          artist_name: "Dua Lipa",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 41,
          track_id: "sWEYPUOZsnk1oTHfyjpJvocYsZm",
          track_name: "The Box",
          artist_name: "Roddy Ricch",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 42,
          track_id: "qVJWXSWzRinVeuRgcwdqBClhhBI",
          track_name: "out of sight (feat. 2 Chainz)",
          artist_name: "Run the Jewels",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 43,
          track_id: "lhw9QVloX3ATq35VIGr2qeRG8pX",
          track_name: "holy calamafuck",
          artist_name: "Run the Jewels",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 44,
          track_id: "riyvCrtNDCXiz3cPsEMnKD1qcF4",
          track_name: "Supalonely",
          artist_name: "benee",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 45,
          track_id: "geHFEykL9B64OWrMLf165QgelyM",
          track_name: "walking in the snow",
          artist_name: "Run the Jewels",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 46,
          track_id: "zXc5ocz7iWsjfEuSzwrXeYoMDrP",
          track_name: "death bed (coffee for your head) (feat. beabadoobee)",
          artist_name: "Powfu",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 47,
          track_id: "PTWXpRxIIUwPVVb5aMz5n8tVJAW",
          track_name: "Everything I Wanted",
          artist_name: "Billie Eilish",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 48,
          track_id: "KH0mI5IH4X6y8m2UiQCT6Z76Akr",
          track_name: "7 rings",
          artist_name: "Ariana Grande",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 49,
          track_id: "G29isqNKZhVs1eiXi6q1KFVkbdd",
          track_name: "Mr. Brightside",
          artist_name: "The Killers",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
        {
          id: 50,
          track_id: "8FnBeqecMal9myRDBvHDeqvwDg3",
          track_name: "Hallucinate",
          artist_name: "Dua Lipa",
          genre: "rock",
          acousticness: null,
          danceability: null,
          duration_ms: null,
          energy: null,
          instrumentalness: null,
          key: null,
          liveness: null,
          loudness: null,
          mode: null,
          speechiness: null,
          tempo: null,
          time_signature: null,
          valence: null,
          popularity: null,
        },
      ]);
    });
};
