exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("songs")
    .truncate()
    .then(function () {
      // Inserts seed entries
      return knex("songs").insert([
        {
          id: 1,
          track_id: "K4PX40m8AzHv0bjHWD0b49qmR42",
          track_name: "rAIn oN mE (with aRIaNa gRAndE)",
          artist_name: "Lady Gaga",
          genre: "rock",
          acousticness: 0.2,
          danceability: 0.5,
          duration_ms: 0.7,
          energy: 0,
          instrumentalness: 0.6,
          key: 0.9,
          liveness: 0.8,
          loudness: 0.8,
          mode: 1,
          speechiness: 0.9,
          tempo: 0.7,
          time_signature: 0.6,
          valence: 0.8,
          popularity: 0.7,
        },
        {
          id: 2,
          track_id: "giRpUcL9aAU2HnNGm41HyY2X7cZ",
          track_name: "Blinding Lights",
          artist_name: "The Weeknd",
          genre: "rock",
          acousticness: 0.3,
          danceability: 0.1,
          duration_ms: 0.9,
          energy: 0.3,
          instrumentalness: 0.6,
          key: 0.6,
          liveness: 0.2,
          loudness: 0.4,
          mode: 1,
          speechiness: 0.8,
          tempo: 0.3,
          time_signature: 0.5,
          valence: 0.4,
          popularity: 0.8,
        },
        {
          id: 3,
          track_id: "Ao0jRDqhrdqZPyPFc1ZjxsQa00R",
          track_name: "Sour Candy (with BLACKPINK)",
          artist_name: "Lady Gaga",
          genre: "classical",
          acousticness: 0.6,
          danceability: 0.7,
          duration_ms: 0.1,
          energy: 0.2,
          instrumentalness: 0.5,
          key: 0.2,
          liveness: 0.9,
          loudness: 0.7,
          mode: 1,
          speechiness: 0.3,
          tempo: 0.5,
          time_signature: 0.6,
          valence: 0.8,
          popularity: 0,
        },
        {
          id: 4,
          track_id: "MyMSkRXVmiN7bBE6T7BJBp96IEF",
          track_name: "Stupid Love",
          artist_name: "Lady Gaga",
          genre: "rock",
          acousticness: 0.2,
          danceability: 0.5,
          duration_ms: 0.3,
          energy: 0.3,
          instrumentalness: 0.2,
          key: 0.9,
          liveness: 0,
          loudness: 0.4,
          mode: 1,
          speechiness: 1,
          tempo: 0.2,
          time_signature: 0,
          valence: 0.8,
          popularity: 0.9,
        },
        {
          id: 5,
          track_id: "L1AZshspXvtGtZUlhIwsvWbnTBE",
          track_name: "Alice",
          artist_name: "Lady Gaga",
          genre: "classical",
          acousticness: 0.3,
          danceability: 0.5,
          duration_ms: 0.8,
          energy: 0.1,
          instrumentalness: 0.9,
          key: 0.8,
          liveness: 0.5,
          loudness: 0,
          mode: 1,
          speechiness: 0.8,
          tempo: 0.8,
          time_signature: 0.3,
          valence: 0.8,
          popularity: 0.8,
        },
        {
          id: 6,
          track_id: "SjtvWFaHeuoqCrazyKUCOC4jU7S",
          track_name: "doN'T StArT nOw",
          artist_name: "Dua Lipa",
          genre: "classical",
          acousticness: 0.8,
          danceability: 0,
          duration_ms: 0.6,
          energy: 0.8,
          instrumentalness: 0.1,
          key: 0.9,
          liveness: 0.4,
          loudness: 0.7,
          mode: 1,
          speechiness: 0.8,
          tempo: 0.1,
          time_signature: 0.2,
          valence: 0.8,
          popularity: 0.6,
        },
        {
          id: 7,
          track_id: "vUS2TMjAX7u4VyYq7Ygdz3XFhi9",
          track_name: "Chromatica I",
          artist_name: "Lady Gaga",
          genre: "pop",
          acousticness: 0.8,
          danceability: 0.8,
          duration_ms: 0.4,
          energy: 0.5,
          instrumentalness: 0.3,
          key: 0.5,
          liveness: 0.7,
          loudness: 1,
          mode: 1,
          speechiness: 0.1,
          tempo: 0,
          time_signature: 0.4,
          valence: 0.2,
          popularity: 0.7,
        },
        {
          id: 8,
          track_id: "oBaIaCVoIG0MkSfcso60VswBhgN",
          track_name: "Free Woman",
          artist_name: "Lady Gaga",
          genre: "rock",
          acousticness: 0,
          danceability: 0.7,
          duration_ms: 0.5,
          energy: 0.8,
          instrumentalness: 0.6,
          key: 0.3,
          liveness: 0.3,
          loudness: 0.4,
          mode: 1,
          speechiness: 0.7,
          tempo: 0.9,
          time_signature: 0.4,
          valence: 1,
          popularity: 0.4,
        },
        {
          id: 9,
          track_id: "ZcvIEoHVpmJhZfcS27SZXu5soQZ",
          track_name: "911",
          artist_name: "Lady Gaga",
          genre: "pop",
          acousticness: 0.9,
          danceability: 0.1,
          duration_ms: 0,
          energy: 0.1,
          instrumentalness: 0.1,
          key: 0.3,
          liveness: 0.6,
          loudness: 0.3,
          mode: 1,
          speechiness: 0.8,
          tempo: 0.2,
          time_signature: 0.9,
          valence: 0.2,
          popularity: 0.7,
        },
        {
          id: 10,
          track_id: "AwGwhPC0dW2zdIxqjUthAOe6upL",
          track_name: "Break My Heart",
          artist_name: "Dua Lipa",
          genre: "rap",
          acousticness: 0.2,
          danceability: 0.5,
          duration_ms: 0.8,
          energy: 0.5,
          instrumentalness: 0.1,
          key: 0.3,
          liveness: 1,
          loudness: 0.5,
          mode: 1,
          speechiness: 0.6,
          tempo: 0.8,
          time_signature: 0.1,
          valence: 0.4,
          popularity: 0.6,
        },
        {
          id: 11,
          track_id: "zqkuG6FcXIpDOdWAQGe2WxUC4d3",
          track_name: "Fun Tonight",
          artist_name: "Lady Gaga",
          genre: "rap",
          acousticness: 1,
          danceability: 0.2,
          duration_ms: 0.9,
          energy: 0.5,
          instrumentalness: 0.2,
          key: 0.4,
          liveness: 0.9,
          loudness: 0.4,
          mode: 1,
          speechiness: 0.4,
          tempo: 0.1,
          time_signature: 0.2,
          valence: 0.8,
          popularity: 0.2,
        },
        {
          id: 12,
          track_id: "gEukmNmrHmwpEdM79nrSDeqLxmF",
          track_name: "Chromatica II",
          artist_name: "Lady Gaga",
          genre: "pop",
          acousticness: 0,
          danceability: 0.8,
          duration_ms: 0.2,
          energy: 0.4,
          instrumentalness: 0.2,
          key: 0,
          liveness: 0.6,
          loudness: 0.3,
          mode: 1,
          speechiness: 0.1,
          tempo: 0.5,
          time_signature: 0.6,
          valence: 0,
          popularity: 0.4,
        },
        {
          id: 13,
          track_id: "3g3hn7FF2l442Vin0Dv9GifoZf5",
          track_name: "Plastic Doll",
          artist_name: "Lady Gaga",
          genre: "classical",
          acousticness: 0.5,
          danceability: 0.5,
          duration_ms: 0.2,
          energy: 0.5,
          instrumentalness: 0.8,
          key: 0.9,
          liveness: 0.2,
          loudness: 0.9,
          mode: 1,
          speechiness: 0.3,
          tempo: 0.6,
          time_signature: 0.1,
          valence: 0.9,
          popularity: 0.6,
        },
        {
          id: 14,
          track_id: "RXxdQImGCtevZLajfcBxHbLfPc7",
          track_name: "Enigma",
          artist_name: "Lady Gaga",
          genre: "pop",
          acousticness: 0.1,
          danceability: 0,
          duration_ms: 0.5,
          energy: 0.7,
          instrumentalness: 0.5,
          key: 0.5,
          liveness: 0.2,
          loudness: 0.1,
          mode: 1,
          speechiness: 0.7,
          tempo: 0.1,
          time_signature: 0.9,
          valence: 0.3,
          popularity: 0.8,
        },
        {
          id: 15,
          track_id: "VQTsx1D5O6YEDEyh0nEYKzBk0Cu",
          track_name: "Replay",
          artist_name: "Lady Gaga",
          genre: "pop",
          acousticness: 0.1,
          danceability: 0.6,
          duration_ms: 0.9,
          energy: 0.7,
          instrumentalness: 0.4,
          key: 0.3,
          liveness: 0.5,
          loudness: 0.7,
          mode: 1,
          speechiness: 0.9,
          tempo: 0.8,
          time_signature: 0.7,
          valence: 0,
          popularity: 0.4,
        },
        {
          id: 16,
          track_id: "xOy3zcev2apQfL5OKGE2UZyMq3Z",
          track_name: "Babylon",
          artist_name: "Lady Gaga",
          genre: "rock",
          acousticness: 0.2,
          danceability: 0,
          duration_ms: 1,
          energy: 0.9,
          instrumentalness: 0.4,
          key: 0.3,
          liveness: 0.1,
          loudness: 0.8,
          mode: 1,
          speechiness: 0.2,
          tempo: 0.8,
          time_signature: 0.7,
          valence: 0.6,
          popularity: 0.8,
        },
        {
          id: 17,
          track_id: "7293hBNN1iG3CeOCN4Nroqev5jh",
          track_name: "1000 Doves",
          artist_name: "Lady Gaga",
          genre: "rap",
          acousticness: 0.1,
          danceability: 0.6,
          duration_ms: 0.1,
          energy: 0.4,
          instrumentalness: 0.3,
          key: 0.4,
          liveness: 0.4,
          loudness: 0.8,
          mode: 1,
          speechiness: 0.2,
          tempo: 0.9,
          time_signature: 0.9,
          valence: 0.8,
          popularity: 0.6,
        },
        {
          id: 18,
          track_id: "2fw9L13kCajph8EpNGyH42AlA8M",
          track_name: "Watermelon Sugar",
          artist_name: "Harry Styles",
          genre: "classical",
          acousticness: 0.9,
          danceability: 0.6,
          duration_ms: 0.8,
          energy: 0.1,
          instrumentalness: 0.8,
          key: 0.4,
          liveness: 0.7,
          loudness: 0.6,
          mode: 1,
          speechiness: 0.6,
          tempo: 0.3,
          time_signature: 0.3,
          valence: 0.8,
          popularity: 0.6,
        },
        {
          id: 19,
          track_id: "uMC2HpPEiZdO0pplLcNStiDd4wf",
          track_name: "Sine From Above (with Elton John)",
          artist_name: "Lady Gaga",
          genre: "pop",
          acousticness: 0.1,
          danceability: 0.5,
          duration_ms: 0.2,
          energy: 0.9,
          instrumentalness: 0.4,
          key: 0.2,
          liveness: 0.2,
          loudness: 0.3,
          mode: 1,
          speechiness: 0.8,
          tempo: 0.9,
          time_signature: 0.3,
          valence: 0.3,
          popularity: 0,
        },
        {
          id: 20,
          track_id: "roDMqueqfNOrBW857Vo9bBI10HT",
          track_name: "Physical",
          artist_name: "Dua Lipa",
          genre: "rap",
          acousticness: 0.6,
          danceability: 0.9,
          duration_ms: 0.5,
          energy: 0.9,
          instrumentalness: 0.9,
          key: 0.9,
          liveness: 0.2,
          loudness: 0.2,
          mode: 1,
          speechiness: 0.4,
          tempo: 0.7,
          time_signature: 0.9,
          valence: 0.2,
          popularity: 0.1,
        },
        {
          id: 21,
          track_id: "s3vyo2E1bwdr65m1IiMCuKdJENT",
          track_name: "Say So",
          artist_name: "Doja Cat",
          genre: "rock",
          acousticness: 0.9,
          danceability: 0.1,
          duration_ms: 0.4,
          energy: 0.1,
          instrumentalness: 0.4,
          key: 0.4,
          liveness: 0.4,
          loudness: 0.4,
          mode: 1,
          speechiness: 0.1,
          tempo: 0.6,
          time_signature: 0.1,
          valence: 0.2,
          popularity: 0.8,
        },
        {
          id: 22,
          track_id: "AjpaA8m6PEfqK5h6M6Zwk0KDjVo",
          track_name: "Adore You",
          artist_name: "Harry Styles",
          genre: "rock",
          acousticness: 0.7,
          danceability: 0.6,
          duration_ms: 0.8,
          energy: 0.2,
          instrumentalness: 0.8,
          key: 0.8,
          liveness: 0.3,
          loudness: 0.2,
          mode: 1,
          speechiness: 0.4,
          tempo: 0,
          time_signature: 0.9,
          valence: 0.6,
          popularity: 0.4,
        },
        {
          id: 23,
          track_id: "Nl4u6cYT2LMAt7MjY7dXXKNcG61",
          track_name: "In Your Eyes",
          artist_name: "The Weeknd",
          genre: "classical",
          acousticness: 0.4,
          danceability: 0.6,
          duration_ms: 0.4,
          energy: 0.7,
          instrumentalness: 0.4,
          key: 0.7,
          liveness: 0.5,
          loudness: 0.2,
          mode: 1,
          speechiness: 0.9,
          tempo: 1,
          time_signature: 0.7,
          valence: 1,
          popularity: 0.2,
        },
        {
          id: 24,
          track_id: "jkOn5lcSq9aVAdsX8BLii0OPquG",
          track_name: "The Less I Know the Better",
          artist_name: "Tame Impala",
          genre: "pop",
          acousticness: 0.2,
          danceability: 0.1,
          duration_ms: 0.1,
          energy: 0.4,
          instrumentalness: 0.2,
          key: 0.9,
          liveness: 0.3,
          loudness: 0.2,
          mode: 1,
          speechiness: 0.2,
          tempo: 0.2,
          time_signature: 1,
          valence: 0.9,
          popularity: 1,
        },
        {
          id: 25,
          track_id: "8gkefLP9BTsnBRljHXkdxfFLNtX",
          track_name: "bad guy",
          artist_name: "Billie Eilish",
          genre: "rock",
          acousticness: 0.7,
          danceability: 0.1,
          duration_ms: 0,
          energy: 0.3,
          instrumentalness: 0.5,
          key: 0.5,
          liveness: 0.8,
          loudness: 0.2,
          mode: 1,
          speechiness: 0,
          tempo: 0.1,
          time_signature: 0.4,
          valence: 0.7,
          popularity: 0,
        },
        {
          id: 26,
          track_id: "otPbIiP0wSpKhQVCr57xRQSEmfx",
          track_name: "TKN (feat. Travis Scott)",
          artist_name: "Rosalía",
          genre: "rap",
          acousticness: 0,
          danceability: 0,
          duration_ms: 0.1,
          energy: 0.3,
          instrumentalness: 0.6,
          key: 1,
          liveness: 0.6,
          loudness: 0.8,
          mode: 1,
          speechiness: 0.1,
          tempo: 0.1,
          time_signature: 1,
          valence: 0.5,
          popularity: 0.5,
        },
        {
          id: 27,
          track_id: "qJgLqeHRE9X68hC3Cygr6HhvYCM",
          track_name: "ROCKSTAR (feat. Roddy Ricch)",
          artist_name: "DaBaby",
          genre: "classical",
          acousticness: 0.6,
          danceability: 0.9,
          duration_ms: 0.5,
          energy: 0.1,
          instrumentalness: 0.6,
          key: 0.9,
          liveness: 0.8,
          loudness: 0.5,
          mode: 1,
          speechiness: 0.6,
          tempo: 0.8,
          time_signature: 0.9,
          valence: 1,
          popularity: 0.3,
        },
        {
          id: 28,
          track_id: "pkecQdk0Mg82ktslT1akCcFZ89l",
          track_name: "This Is America",
          artist_name: "Childish Gambino",
          genre: "rap",
          acousticness: 0,
          danceability: 0.7,
          duration_ms: 0.5,
          energy: 0.9,
          instrumentalness: 1,
          key: 0.8,
          liveness: 0.6,
          loudness: 1,
          mode: 1,
          speechiness: 0.3,
          tempo: 0.7,
          time_signature: 0.8,
          valence: 0.4,
          popularity: 0,
        },
        {
          id: 29,
          track_id: "DEpkeReGVabNKRZXkzBSeTnz0wv",
          track_name: "Roses - Imanbek Remix",
          artist_name: "SAINt JHN",
          genre: "rap",
          acousticness: 0.6,
          danceability: 0.4,
          duration_ms: 0.9,
          energy: 0.4,
          instrumentalness: 0.9,
          key: 0.3,
          liveness: 0.2,
          loudness: 0.6,
          mode: 1,
          speechiness: 0.9,
          tempo: 0.8,
          time_signature: 0,
          valence: 0.6,
          popularity: 0.1,
        },
        {
          id: 30,
          track_id: "qUOMeYyhGYLjFf9ZShn974Ske3F",
          track_name: "Alright",
          artist_name: "Kendrick Lamar",
          genre: "pop",
          acousticness: 0.2,
          danceability: 0.7,
          duration_ms: 1,
          energy: 0.7,
          instrumentalness: 0.9,
          key: 0.5,
          liveness: 0.2,
          loudness: 0.3,
          mode: 1,
          speechiness: 0.6,
          tempo: 0.2,
          time_signature: 0.5,
          valence: 0.7,
          popularity: 0.7,
        },
        {
          id: 31,
          track_id: "2hinUYDEwrMyDkKdsDeSmNkmVaf",
          track_name: "Toosie Slide",
          artist_name: "Drake",
          genre: "pop",
          acousticness: 0.7,
          danceability: 0.3,
          duration_ms: 0,
          energy: 0.5,
          instrumentalness: 0.7,
          key: 0.2,
          liveness: 0.3,
          loudness: 0.6,
          mode: 1,
          speechiness: 1,
          tempo: 0.4,
          time_signature: 0.3,
          valence: 0.1,
          popularity: 0.6,
        },
        {
          id: 32,
          track_id: "7BrmBo59xLHnoOngmMeF72K6rb1",
          track_name: "Savage Remix (feat. Beyoncé)",
          artist_name: "Megan Thee Stallion",
          genre: "rock",
          acousticness: 0.8,
          danceability: 0.9,
          duration_ms: 0.8,
          energy: 1,
          instrumentalness: 1,
          key: 0.6,
          liveness: 0.9,
          loudness: 1,
          mode: 1,
          speechiness: 0.2,
          tempo: 0.1,
          time_signature: 0.8,
          valence: 0.5,
          popularity: 0.9,
        },
        {
          id: 33,
          track_id: "vHzSXodx3L7GLL6fTun7nipMhdM",
          track_name: "yankee and the brave (ep. 4)",
          artist_name: "Run the Jewels",
          genre: "rap",
          acousticness: 0.3,
          danceability: 0.3,
          duration_ms: 0.2,
          energy: 0,
          instrumentalness: 0.7,
          key: 0.4,
          liveness: 0.3,
          loudness: 0.1,
          mode: 1,
          speechiness: 0.4,
          tempo: 0.4,
          time_signature: 0.9,
          valence: 0.7,
          popularity: 0.2,
        },
        {
          id: 34,
          track_id: "cxEgpjkDjGFGBVBuCKxdRkthX2K",
          track_name: "Earfquake",
          artist_name: "Tyler, the Creator",
          genre: "rock",
          acousticness: 1,
          danceability: 0.7,
          duration_ms: 0.1,
          energy: 0.5,
          instrumentalness: 0.9,
          key: 0.3,
          liveness: 0.8,
          loudness: 0.1,
          mode: 1,
          speechiness: 0.1,
          tempo: 0.3,
          time_signature: 0.7,
          valence: 0.7,
          popularity: 0.8,
        },
        {
          id: 35,
          track_id: "qJkQftzqdTX6gEubE13FzLPL7MG",
          track_name: "THE SCOTTS",
          artist_name: "Scotts",
          genre: "pop",
          acousticness: 0.7,
          danceability: 0.9,
          duration_ms: 0.1,
          energy: 0.3,
          instrumentalness: 0.6,
          key: 0.7,
          liveness: 0.7,
          loudness: 0.5,
          mode: 1,
          speechiness: 0.6,
          tempo: 0.5,
          time_signature: 0.3,
          valence: 0.3,
          popularity: 1,
        },
        {
          id: 36,
          track_id: "G5WgmBJQjt0irhoorRm2iSSVuKT",
          track_name: "Circles",
          artist_name: "Post Malone",
          genre: "pop",
          acousticness: 0.8,
          danceability: 0.6,
          duration_ms: 0.7,
          energy: 0.1,
          instrumentalness: 0.6,
          key: 0.1,
          liveness: 0,
          loudness: 1,
          mode: 1,
          speechiness: 0.3,
          tempo: 0.2,
          time_signature: 0.7,
          valence: 0.9,
          popularity: 0.2,
        },
        {
          id: 37,
          track_id: "x6QdVA8NYLtz2SkWTXK2gr8Chj8",
          track_name: "Boss Bitch",
          artist_name: "Doja Cat",
          genre: "rock",
          acousticness: 1,
          danceability: 0.9,
          duration_ms: 0.7,
          energy: 0,
          instrumentalness: 0.3,
          key: 0.2,
          liveness: 0.2,
          loudness: 0.3,
          mode: 1,
          speechiness: 0.4,
          tempo: 0.3,
          time_signature: 0.8,
          valence: 0.1,
          popularity: 0.4,
        },
        {
          id: 38,
          track_id: "kCeAyN81ms06TqMOT0bJIKEdVJO",
          track_name: "Ooh La La (feat. Greg Nice & DJ Premier)",
          artist_name: "Run the Jewels",
          genre: "rap",
          acousticness: 0.3,
          danceability: 0.2,
          duration_ms: 0.9,
          energy: 0.5,
          instrumentalness: 0.3,
          key: 0.5,
          liveness: 0.4,
          loudness: 0.9,
          mode: 1,
          speechiness: 0.8,
          tempo: 0.5,
          time_signature: 0.9,
          valence: 0.6,
          popularity: 0.3,
        },
        {
          id: 39,
          track_id: "DGdFaOYnK1QK1VD7DIqZKDqamGT",
          track_name: "JU$T (feat. Pharrell Williams & Zack de la Rocha)",
          artist_name: "Run the Jewels",
          genre: "pop",
          acousticness: 0.6,
          danceability: 0.7,
          duration_ms: 0.5,
          energy: 0.7,
          instrumentalness: 0.9,
          key: 0.6,
          liveness: 0.7,
          loudness: 0.3,
          mode: 1,
          speechiness: 0.3,
          tempo: 0.6,
          time_signature: 0.1,
          valence: 0.9,
          popularity: 0.5,
        },
        {
          id: 40,
          track_id: "kkAD3lQ2rDlc698nHQCXk9nx4Cm",
          track_name: "Levitating",
          artist_name: "Dua Lipa",
          genre: "rock",
          acousticness: 0.4,
          danceability: 0.7,
          duration_ms: 1,
          energy: 0.7,
          instrumentalness: 0.5,
          key: 0.5,
          liveness: 0.8,
          loudness: 0.6,
          mode: 1,
          speechiness: 0.5,
          tempo: 0,
          time_signature: 0.1,
          valence: 0.1,
          popularity: 0.5,
        },
        {
          id: 41,
          track_id: "aGthA1dfF22cXGsgtxNU1RUvVKB",
          track_name: "The Box",
          artist_name: "Roddy Ricch",
          genre: "pop",
          acousticness: 0.9,
          danceability: 0,
          duration_ms: 0.4,
          energy: 0.7,
          instrumentalness: 0.8,
          key: 0.1,
          liveness: 0.6,
          loudness: 0.9,
          mode: 1,
          speechiness: 0.1,
          tempo: 0.2,
          time_signature: 0.3,
          valence: 0,
          popularity: 0.1,
        },
        {
          id: 42,
          track_id: "ysOfsdTWJAH47rxaNJulwjeZiTr",
          track_name: "out of sight (feat. 2 Chainz)",
          artist_name: "Run the Jewels",
          genre: "classical",
          acousticness: 0.3,
          danceability: 0.1,
          duration_ms: 0.3,
          energy: 0.9,
          instrumentalness: 0.5,
          key: 0.1,
          liveness: 0.9,
          loudness: 0.6,
          mode: 1,
          speechiness: 0.2,
          tempo: 0.2,
          time_signature: 0.8,
          valence: 0,
          popularity: 0.6,
        },
        {
          id: 43,
          track_id: "BzTfecl4h7eE2Tg32QpijnwAOAb",
          track_name: "holy calamafuck",
          artist_name: "Run the Jewels",
          genre: "rock",
          acousticness: 0.1,
          danceability: 0.5,
          duration_ms: 0.7,
          energy: 0.7,
          instrumentalness: 0.4,
          key: 0.4,
          liveness: 0.4,
          loudness: 0.9,
          mode: 1,
          speechiness: 0.6,
          tempo: 0.9,
          time_signature: 0.8,
          valence: 0.5,
          popularity: 0.7,
        },
        {
          id: 44,
          track_id: "shyv8HBJFmIW7VSzk64zkrc6N0t",
          track_name: "Supalonely",
          artist_name: "benee",
          genre: "classical",
          acousticness: 0.4,
          danceability: 0.2,
          duration_ms: 0.7,
          energy: 0.5,
          instrumentalness: 0.4,
          key: 0.3,
          liveness: 0.4,
          loudness: 0.4,
          mode: 1,
          speechiness: 0.3,
          tempo: 0.6,
          time_signature: 0.6,
          valence: 0.6,
          popularity: 0.2,
        },
        {
          id: 45,
          track_id: "EwRFSqbkXxLD80oxAyLlGTt9Qod",
          track_name: "walking in the snow",
          artist_name: "Run the Jewels",
          genre: "rap",
          acousticness: 0.8,
          danceability: 0.2,
          duration_ms: 0.5,
          energy: 1,
          instrumentalness: 1,
          key: 0.8,
          liveness: 0.7,
          loudness: 0.3,
          mode: 1,
          speechiness: 0.7,
          tempo: 0.3,
          time_signature: 0.3,
          valence: 0.8,
          popularity: 0.4,
        },
        {
          id: 46,
          track_id: "b6q09H0PFv35bcJkGZNqrjhL018",
          track_name: "death bed (coffee for your head) (feat. beabadoobee)",
          artist_name: "Powfu",
          genre: "rock",
          acousticness: 0.4,
          danceability: 1,
          duration_ms: 0.4,
          energy: 0.2,
          instrumentalness: 0.7,
          key: 0.6,
          liveness: 0.2,
          loudness: 0.5,
          mode: 1,
          speechiness: 1,
          tempo: 0.4,
          time_signature: 0.9,
          valence: 0.3,
          popularity: 1,
        },
        {
          id: 47,
          track_id: "BsLNuMsX8NsJOo0N9gQXAVorWtz",
          track_name: "Everything I Wanted",
          artist_name: "Billie Eilish",
          genre: "rock",
          acousticness: 0.6,
          danceability: 0,
          duration_ms: 0.8,
          energy: 0.5,
          instrumentalness: 0.3,
          key: 0.5,
          liveness: 0.7,
          loudness: 0.9,
          mode: 1,
          speechiness: 0.4,
          tempo: 0.8,
          time_signature: 0.9,
          valence: 0.1,
          popularity: 0.5,
        },
        {
          id: 48,
          track_id: "YS4uveRsmnFMdLlpdlTiNDRpVH6",
          track_name: "7 rings",
          artist_name: "Ariana Grande",
          genre: "rock",
          acousticness: 0.8,
          danceability: 0.4,
          duration_ms: 0.2,
          energy: 0.4,
          instrumentalness: 0.6,
          key: 0.7,
          liveness: 0,
          loudness: 0.8,
          mode: 1,
          speechiness: 0.7,
          tempo: 0.1,
          time_signature: 0.1,
          valence: 0.5,
          popularity: 0.9,
        },
        {
          id: 49,
          track_id: "ZtwWpaVxVwGTXUPFZAAF3RuR9W5",
          track_name: "Mr. Brightside",
          artist_name: "The Killers",
          genre: "classical",
          acousticness: 1,
          danceability: 0.3,
          duration_ms: 0.8,
          energy: 0.8,
          instrumentalness: 0.8,
          key: 1,
          liveness: 0.1,
          loudness: 0.8,
          mode: 1,
          speechiness: 0.7,
          tempo: 0.1,
          time_signature: 0.5,
          valence: 0.7,
          popularity: 0.8,
        },
        {
          id: 50,
          track_id: "zR4dIlz9o58Wi9d5oDU0FzGqH65",
          track_name: "Hallucinate",
          artist_name: "Dua Lipa",
          genre: "pop",
          acousticness: 0.4,
          danceability: 0.2,
          duration_ms: 0.5,
          energy: 0.7,
          instrumentalness: 0.3,
          key: 0.7,
          liveness: 0.9,
          loudness: 0.8,
          mode: 1,
          speechiness: 0.3,
          tempo: 0,
          time_signature: 0.4,
          valence: 0.4,
          popularity: 0.8,
        },
      ]);
    });
};
